# Generated by Django 2.1.7 on 2019-05-28 11:11

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', django_jalali.db.models.jDateField()),
                ('day_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DayRange')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='final_exam_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_exams', to='users.ExamDate'),
        ),
        migrations.AlterField(
            model_name='course',
            name='midterm_exam_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midterm_exams', to='users.ExamDate'),
        ),
        migrations.AlterUniqueTogether(
            name='examdate',
            unique_together={('day_range', 'day')},
        ),
    ]
