# Generated by Django 2.1.7 on 2019-05-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190528_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='departments',
        ),
        migrations.AddField(
            model_name='field',
            name='other_departments',
            field=models.ManyToManyField(blank=True, related_name='fields', to='users.Department'),
        ),
    ]
