# Generated by Django 2.1.7 on 2019-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190528_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='nickname',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
